### ISSUE TITLE
Add option to set Min/Max values before indexing

### ISSUE THREAD

**Issue by Adricu8** [Qbeast-io/qbeast-spark#157]
It is an important feature to add to the format to be able to control how the range of the cubes are formed when dealing with streaming or event-based data. The reason is that otherwise we have to create a new revision every time new data arrives (assuming a timestamp column is indexed), and also rewriting the index too frequently can be very expensive. 

We could add the option to customize the min/max values for specific columns.
The following snippet code is just an example on what would be needed:

### Example code

```scala
val df = spark.read.parquet("event-based-data.parquet")
df.write.format("qbeast").options(Map("columnsToIndex" -> "timestamp,other_column", "cubeSize" -> "5000", "min:timestamp" -> "1919191919", "max:timestamp" -> "2020202020")).save("tmpTable")
```

In this way, we can control how often the index will create a new revision on specific use-cases.

**Comment by osopardo1** [comment]
Hello @Adricu8 !!

I propose a different API for adding min and max values:

```scala
df.write.format("qbeast").options(Map("columnsToIndex" -> "timestamp(min:19191919,max:202020),other_column", "cubeSize" -> "5000")).save("tmpTable")
```

Let me know which one do you prefer 😄

**Comment by Adricu8** [comment]
Hi Paola, I think your proposal is nice! :)

**Comment by osopardo1** [comment]
After some research, I will try to implement the option you propose in the beginning!

Because to calculate the `Transformations` (which are the **objects that contain min and max data**) we use an Spark Row that has the following structure:

```scala
"min(columnName)=1, max(columnName)=2"
```

**We can use the same structure in another optional parameter** that users can copy and paste from their spark applications.

```scala
df.write.format("qbeast").options(Map("columnsToIndex" -> "timestamp,other_column", "cubeSize" -> "5000", "stats" -> "(min(timestamp)=1, max(timestamp)=3)").save("tmpTable")
``` 

I am currently exploring this option, sorry for any possible confusion! 

I will come back with the final resolution soon.
