### ISSUE TITLE
Why do we read twice the delta log when doing a query?

### ISSUE THREAD

**Issue by cugni** [Qbeast-io/qbeast-spark#61]
In the current implementation, when we do a query, we read at least twice the delta log: 
1. At first, in the OTreeIndex:33 class, when we call 
```scala
val tahoeMatchingFiles = index.matchingFiles(partitionFilters, dataFilters)
```
on the TahoeLogFileIndex
2. Then in QueryExecutor:28 when we execute
```scala
val indexStatus = qbeastSnapshot.loadIndexStatus(revision.revisionID)
```
 we read the full deltaLog once for each revision. 

Also, we do an intersection of the files in **tahoeMatchingFiles** and the files found by the QueryExecutor twice, one explicitly in OTreeIndex:41
```scala
 tahoeMatchingFiles.filter { a => qbeastMatchingFiles.exists(_.path == a.path) }
```
and also when we do the flatMap in the QueryExecutor:63
```scala
outputFiles ++= files.flatMap(fileMap.get)
```

The questions are:
1. Do we need to filter also for the tahoeIndexFiles? Which are the data predicates that it filters that we don't? 
2. If we need to use the file matched by the TahoeLogFileIndex, why don't we use these files to build the IndexStatus, so we don't have to scan the deltaLog multiple times, and we don't have to intersect the list of files.

**Comment by osopardo1** [comment]
A few thoughts:

1. The filtering that `tahoeIndexFiles` does in the open-source version is only **partition pruning**. Since we are not using partitioning in the Qbeast Format scenario, there's no need to filter before. However, in the private version and maybe future Delta Lake enhancements, they could include some extra filtering. If we want to support other types of file-skipping techniques, we should either delegate or implement them ourselves.
2. I don't know which could be the consequences of building the `IndexStatus` with a **subset** of files. Probably the structure of the cube statuses gets affected. If not, the ideal scenario would be to build them with the previous set of matching files.
